openapi: 3.1.0
info:
  title: User Management API
  summary: REST APIs for managing user accounts and sessions
  version: '1.0'
servers:
  - url: http://localhost:3000/v1
    description: Local development environment
paths:
  /users/{userId}:
    get:
      operationId: get-user
      summary: Retrieve user details 
      description: Retrieve details of a specific user by their unique ID, or retrieve the logged-in user's profile using "me" in the ongoing session.
      parameters:
        - name: userId
          in: path
          required: true
          description: the unique identifier of the user. Use "me" to fetch the logged-in user's profile. 
          schema: 
            type: string 
      responses:
        200:
          description: Successfully retrieved the user details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        401:
          description: Unauthorized - User not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        403: 
          description: Forbidden - User lacks permission to retrieve this data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRersponse'
        404:
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'     
    delete:
      operationId: delete-user
      summary: Delete a user account
      description: Permanently delete a user account by their unique user ID. 
      parameters:
        - name: userId
          in: path
          required: true
          description: The unique identifier of the user to delete. 
          schema:
            type: string
      responses:
        200:
          description: Successfully deleted the user account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        401:
          description: Unauthorized request - User not authenticated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        403:
          description: Forbidden - User lacks permission to delete this account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse' 
        404:
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal server error 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'     
  /auth/logout:
    post:
      operationId: logout-user
      summary: Log out the current user
      description: Logs out the user from the current session, invalidating any active session tokens.
      responses:
        200:
          description: Successfully logged out the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        401:
          description: Unauthorized - User not logged in
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#components/schemas/ErrorResponse'
components:
  schemas:
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          example: "Operation Successful"
    ErrorResponse:
      type: object
      properties:
        code:
          type: string 
          example: "UNAUTHORIZED"
        message:
          type: string
          example: "User is not authenticated."
    UserProfile:
      type: object
      properties:
        userid:
          type: string
          example: "12345"
        username:
          type: string
          example: "johndoe"
        email:
          type: string
          example: "johndoe@example.com"
        firstName:
          type: string
          example: "John"
        lastName:
          type: string
          example: "Doe"
        createdAt:
          type: string
          format: date-time
          example: "2023-01-01T00:00:00Z"
        updatedAt:
          type: string
          format: date-time
          example: "2023-01-02T12:00:00Z"

#/users/{userId} endpoint now serves dual purposes. 
# 1. /users/me: THis will retrieve the logged-in user's profile details 
# 2. .users/{specificUserId}: Retrieves details of a specific user. 
#the rest of the two endpoints are distinct and therefore no changes are needed. 